export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const LOCATION_CHANGE = 'LOCATION_CHANGE'; // perform some logic to guess if someone entered the scenario
export const TESTING_INIT = 'TESTING_INIT';
export const SESSION_SCORE = 'SESSION_SCORE';
export const SESSION_CREATE = 'SESSION_CREATE';
export const RECORD_SNAPSHOT = 'RECORD_SNAPSHOT';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const CHANGE_ADAPTER = 'CHANGE_ADAPTER';
export const CHANGE_THROTTLE_NETWORK = 'CHANGE_THROTTLE_NETWORK';
export const CHANGE_NETWORK_SPEED = 'CHANGE_NETWORK_SPEED';
export const ADD_STATS= 'ADD_STATS';
export const SUMMARY_QUESTION_ANSWERED = 'SUMMARY_QUESTION_ANSWERED';
export const SEND_SURVEY = 'SEND_SURVEY';
export const SWITCH_INSTRUCTIONS = 'SWITCH_INSTRUCTIONS';
export const FINISH_INTRO = 'FINISH_INTRO';

export const SEND_STARTED = 'SEND_STARTED';
export const SEND_COMPLETE = 'SEND_COMPLETE';
export const SEND_ERROR = 'SEND_ERROR';
export const ADD_ANALYTICS_EVENT = 'ADD_ANALYTICS_EVENT';
