export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const LOCATION_CHANGE = 'LOCATION_CHANGE'; // perform some logic to guess if someone entered the scenario
export const TESTING_INIT = 'TESTING_INIT';
export const SESSION_SCORE = 'SESSION_SCORE';
export const SESSION_CREATE = 'SESSION_CREATE';
export const RECORD_SNAPSHOT = 'RECORD_SNAPSHOT';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const CHANGE_ADAPTER = 'CHANGE_ADAPTER';
export const CHANGE_THROTTLE_NETWORK = 'CHANGE_THROTTLE_NETWORK';
export const CHANGE_NETWORK_SPEED = 'CHANGE_NETWORK_SPEED';
