language: node_js
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - yarn install
cache:
  directories:
  - $HOME/.yarn-cache
node_js:
  - "6"
  - "5"
  - "4"
after_success:
  # Send coverage data to coveralls.
  - npm run test:cover:travis
